name: new_release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
              
    - name: Install dependencies
      run: go get .
      
    - name: Build
      run: go build -v ./...
          
    - name: run tests
      run: go test -json ./... > test.json
        
    - name: Annotate tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.5.1
      with:
        test-results: test.json
        
  image-push:
    
    needs: tests
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Install dependencies
      run: make
    
    - name: Build the Docker image
      run: make docker-build 
      
    - name: push the Docker image
      run: make docker-push IMG=kaparajpg/${{ github.event.repository.name }}
      
